### ISSUE TITLE
Managing form values seperately from stores

### ISSUE THREAD

**Issue by dongheenam** [dongheenam/math-test-builder#12]
At the moment, all the form values are stored and updated in Zustand for simplicity, but it's bloating up.

## Tasks

- [ ] Try out `react-hook-form`
- [ ] Write validate functions
- [ ] Connect `react-hook-form` with Zustand stores

**Comment by dongheenam** [comment]
See #11

**Comment by dongheenam** [comment]
Tried a few different form management libraries (`react-hook-form`, `react-final-form`), they were way too verbose and complicated to work around controlled inputs.
