### ISSUE TITLE
Integrate next-auth with existing functionality

### ISSUE THREAD

**Issue by dongheenam** [dongheenam/math-test-builder#15]
We now need to integrate `next-auth` with the app.

## Tasks

- [ ] Redirect `\questions` to login page if not logged in
- [ ] user id in questions
- [ ] question bucket management
- [ ] user can edit questions locally (to bucket) & globally (to Questions)

**Comment by dongheenam** [comment]
## Progress update

To simplify the logic, buckets are saved in localStorage. They will either be quickly deleted or added to a test anyways.
