### ISSUE TITLE
Create instances for the app

### ISSUE THREAD

**Issue by dongheenam** [dongheenam/math-test-builder#3]
## Tasks

- [x] Create a Vercel instance
- [x] Create a MongoDB Atlas instance
- [ ] Create a CloudFlare Image Hosting instance
